### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by esduh**
Vision statement has been revised according to the following criteria:
- move pandemic comment
- fix ";" usage
- reword "it will do exactly that"

### CODE REVIEW

**Comment by Leo-SIK** [comment]
@kvlinden our vision statement has been revised! Could you please take a look at it when you can and let us know what you think? Thank you!

**Comment by kvlinden** [comment]
The only change I see in this pull request is the change of spelling for Zach's name. I still see the ";", for example.

**Review by kvlinden — CHANGES_REQUESTED** [review]
Fix the two incomplete sentences in the first paragraph and then you're good.

**Comment by esduh** [comment]
Please look at both commits!

**Review by kvlinden — APPROVED** [review]
much better

**Pull request merged**
